
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import CardEscrowContractArtifactJson from './CardEscrow.json' with { type: 'json' };
export const CardEscrowContractArtifact = loadContractArtifact(CardEscrowContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract CardEscrow;
 */
export class CardEscrowContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, CardEscrowContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, CardEscrowContract.artifact, wallet) as Promise<CardEscrowContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, token_address: AztecAddressLike, operator_address: AztecAddressLike, operator_pubkey_x: FieldLike, operator_pubkey_y: FieldLike, spend_limit: (bigint | number)) {
    return new DeployMethod<CardEscrowContract>(PublicKeys.default(), wallet, CardEscrowContractArtifact, CardEscrowContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, token_address: AztecAddressLike, operator_address: AztecAddressLike, operator_pubkey_x: FieldLike, operator_pubkey_y: FieldLike, spend_limit: (bigint | number)) {
    return new DeployMethod<CardEscrowContract>(publicKeys, wallet, CardEscrowContractArtifact, CardEscrowContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof CardEscrowContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<CardEscrowContract['methods'][M]>
  ) {
    return new DeployMethod<CardEscrowContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      CardEscrowContractArtifact,
      CardEscrowContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return CardEscrowContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(CardEscrowContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'config' | 'escrow_nonce' | 'spend_limit' | 'timelocks' | 'timelocks_private' | 'spend_epoch'> {
      return {
        config: {
      slot: new Fr(1n),
    },
escrow_nonce: {
      slot: new Fr(2n),
    },
spend_limit: {
      slot: new Fr(3n),
    },
timelocks: {
      slot: new Fr(4n),
    },
timelocks_private: {
      slot: new Fr(6n),
    },
spend_epoch: {
      slot: new Fr(7n),
    }
      } as ContractStorageLayout<'config' | 'escrow_nonce' | 'spend_limit' | 'timelocks' | 'timelocks_private' | 'spend_epoch'>;
    }
    

  public static get notes(): ContractNotes<'UintNote' | 'TimelockedNote' | 'ConfigNote' | 'SpendLimitNote' | 'EscrowNonceNote' | 'SpentAmountEpochNote'> {
    return {
      UintNote: {
          id: new NoteSelector(0),
        },
TimelockedNote: {
          id: new NoteSelector(5),
        },
ConfigNote: {
          id: new NoteSelector(1),
        },
SpendLimitNote: {
          id: new NoteSelector(3),
        },
EscrowNonceNote: {
          id: new NoteSelector(2),
        },
SpentAmountEpochNote: {
          id: new NoteSelector(4),
        }
    } as ContractNotes<'UintNote' | 'TimelockedNote' | 'ConfigNote' | 'SpendLimitNote' | 'EscrowNonceNote' | 'SpentAmountEpochNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** bump_escrow_nonce() */
    bump_escrow_nonce: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cancel_timelocks(spend_limit: boolean, withdraw: boolean) */
    cancel_timelocks: ((spend_limit: boolean, withdraw: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** change_spend_limit(new_spend_limit: integer) */
    change_spend_limit: ((new_spend_limit: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** change_spend_limit_by_signature(new_spend_limit: integer, signature: array) */
    change_spend_limit_by_signature: ((new_spend_limit: (bigint | number), signature: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(token_address: struct, operator_address: struct, operator_pubkey_x: field, operator_pubkey_y: field, spend_limit: integer) */
    constructor: ((token_address: AztecAddressLike, operator_address: AztecAddressLike, operator_pubkey_x: FieldLike, operator_pubkey_y: FieldLike, spend_limit: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deposit(amount: integer, _nonce: field) */
    deposit: ((amount: (bigint | number), _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** finalize_spend_limit_change() */
    finalize_spend_limit_change: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config() */
    get_config: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_nonce() */
    get_nonce: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_spend_limit() */
    get_spend_limit: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_timelocks_private() */
    get_timelocks_private: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_timelocks_public() */
    get_timelocks_public: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** prepare_withdrawal(amount: integer) */
    prepare_withdrawal: ((amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** spend(amount: integer, epoch: field) */
    spend: ((amount: (bigint | number), epoch: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw(amount: integer) */
    withdraw: ((amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw_by_signature(amount: integer, signature: array) */
    withdraw_by_signature: ((amount: (bigint | number), signature: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
